spring.application.name=quickcart
spring.datasource.url=jdbc:postgresql://localhost:5432/quick_cart
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
pring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true 
spring.jpa.format_sql=true

server.port=8080